
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function POST(request: NextRequest) {
  try {
    const { reportType, dateFilter, items } = await request.json();

    // Import dynamic modules
    const { jsPDF } = await import('jspdf');
    require('jspdf-autotable');

    const doc = new jsPDF('p', 'mm', 'legal'); // Legal size (8.5" x 14")
    
    // Add logo (placeholder for now - you can add actual logo later)
    doc.setFillColor(0, 0, 0);
    doc.rect(15, 15, 30, 20, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(12);
    doc.text('LOGO', 30, 27);
    
    // Reset text color
    doc.setTextColor(0, 0, 0);
    
    // Header
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('INVENTORY MANAGEMENT SYSTEM', 50, 25);
    
    doc.setFontSize(16);
    doc.text('Animal Feed Supply Store', 50, 35);
    
    // Report title
    doc.setFontSize(18);
    let reportTitle = '';
    switch (reportType) {
      case 'history':
        reportTitle = 'TRANSACTION HISTORY REPORT';
        break;
      case 'outOfStock':
        reportTitle = 'OUT OF STOCK PRODUCTS REPORT';
        break;
      case 'inStock':
        reportTitle = 'IN STOCK PRODUCTS REPORT';
        break;
    }
    doc.text(reportTitle, 15, 55);
    
    // Date and time
    const now = new Date();
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated on: ${now.toLocaleDateString()} at ${now.toLocaleTimeString()}`, 15, 65);
    
    if (reportType === 'history' && dateFilter) {
      let dateText = 'Report Period: ';
      if (dateFilter.dateType === 'specific') {
        dateText += `${new Date(dateFilter.specificDate).toLocaleDateString()}`;
      } else if (dateFilter.dateType === 'month') {
        const monthName = new Date(2024, parseInt(dateFilter.month) - 1, 1).toLocaleString('default', { month: 'long' });
        dateText += `${monthName} ${dateFilter.year}`;
      } else if (dateFilter.dateType === 'year') {
        dateText += `Year ${dateFilter.year}`;
      }
      doc.text(dateText, 15, 75);
    }
    
    // Table data
    let tableData: any[][] = [];
    let headers: string[] = [];
    
    if (reportType === 'history') {
      // For history, we'll need to fetch actual history data
      const history = await prisma.history.findMany({
        orderBy: { createdAt: 'desc' },
        take: 100, // Limit for demo
      });
      
      headers = ['Date/Time', 'Product', 'Category', 'Action', 'Quantity', 'User'];
      tableData = history.map(record => [
        new Date(record.createdAt).toLocaleDateString() + ' ' + new Date(record.createdAt).toLocaleTimeString(),
        record.itemName,
        record.category,
        record.action.toUpperCase(),
        record.quantity.toString(),
        `User ${record.userId}`
      ]);
    } else {
      headers = ['Product Name', 'Category', 'Stock Quantity', 'Status'];
      tableData = items.map((item: any) => [
        item.name,
        item.category,
        item.stock.toString(),
        item.stock === 0 ? 'OUT OF STOCK' : 'IN STOCK'
      ]);
    }
    
    // Add table
    (doc as any).autoTable({
      head: [headers],
      body: tableData,
      startY: reportType === 'history' ? 85 : 75,
      styles: {
        fontSize: 10,
        cellPadding: 3,
      },
      headStyles: {
        fillColor: [0, 0, 0],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
      },
      alternateRowStyles: {
        fillColor: [245, 245, 245],
      },
      columnStyles: {
        0: { cellWidth: 'auto' },
        1: { cellWidth: 'auto' },
        2: { cellWidth: 'auto' },
        3: { cellWidth: 'auto' },
      },
    });
    
    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text('Generated by Inventory Management System', 15, pageHeight - 20);
    doc.text(`Total Records: ${tableData.length}`, 15, pageHeight - 15);
    doc.text(`Page 1 of 1`, 150, pageHeight - 15);
    
    // Convert to buffer
    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
    
    return new NextResponse(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${reportType}-report-${Date.now()}.pdf"`,
      },
    });
  } catch (error) {
    console.error('PDF generation error:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to generate PDF' },
      { status: 500 }
    );
  }
}
